import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.variable} antialiased`}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
